### ISSUE TITLE
Compatibility with Meteor v2

### ISSUE THREAD

**Issue by pouya-eghbali** [meteor-svelte/meteor-svelte#50] opened 2021-04-23 12:54 UTC
I upgraded my project from 1.12.1 to 2.2 and it looks like the upgrade breaks this package.

I investigated the issue and it seems like on 2.2 the `Babel.getDefaultOptions` call in `transpileWithBabel` returns options with `sourceMaps` set to `false`. Adding a .babelrc or babel.config.json file to the root of the project doesn't solve the issue, as a workaround I added `options.sourceMaps = true;` under `options.filename = path;`.

I'm not sure if I'm doing something wrong, are there any babel or meteor configurations that solve this issue or setting the sourceMaps option in the `transpileWithBabel` file is the way forward?

**Comment by rdb** [comment] 2022-01-23 13:03
Duplicate of #52

**Closed by rdb** 2022-01-23 13:03 UTC
